#!/usr/bin/env python3
"""Build the framework metadata index from a framework registry folder.

    python3 scripts/frameworks/build-index.py <frameworks-dir> <out-dir>

Reads the YAML frontmatter of every <frameworks-dir>/*.md (files starting with "_" and
README.md are skipped), checks it against the required fields, and writes two files:

  <out-dir>/framework-index.yaml       metadata only, no framework bodies; what the router reads
  <out-dir>/framework-vocabulary.yaml  problem type -> framework ids; what the classifier reads

Deterministic: same registry in, same bytes out. Exits non-zero on a malformed framework,
so a broken registry stops a run before any agent is spawned. Adding a framework is adding
one .md file; nothing here changes.
"""
import json
import pathlib
import sys

import yaml

REQUIRED = [
    "id", "name", "purpose", "problemTypes", "useWhen", "doNotUseWhen",
    "questionsAnswered", "requiredEvidence", "outputs", "complexity",
]
LISTS = ["problemTypes", "useWhen", "doNotUseWhen", "questionsAnswered", "requiredEvidence", "outputs"]
OPTIONAL_LISTS = ["overlapsWith", "pairsWellWith"]


def read_frontmatter(path: pathlib.Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError("no YAML frontmatter (file must start with '---')")
    end = text.find("\n---", 4)
    if end == -1:
        raise ValueError("frontmatter is not closed with '---'")
    data = yaml.safe_load(text[4:end])
    if not isinstance(data, dict):
        raise ValueError("frontmatter is not a mapping")
    return data


def check(meta: dict, path: pathlib.Path) -> list:
    errors = [f"missing field '{f}'" for f in REQUIRED if f not in meta]
    errors += [f"'{f}' must be a non-empty list" for f in LISTS
               if f in meta and (not isinstance(meta[f], list) or not meta[f])]
    errors += [f"'{f}' must be a list" for f in OPTIONAL_LISTS
               if f in meta and not isinstance(meta[f], list)]
    if meta.get("id") != path.stem:
        errors.append(f"id '{meta.get('id')}' must equal the file name '{path.stem}'")
    if not isinstance(meta.get("complexity"), int) or not 1 <= meta.get("complexity", 0) <= 5:
        errors.append("'complexity' must be an integer 1-5")
    return errors


def main(argv: list) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    registry, out_dir = pathlib.Path(argv[1]), pathlib.Path(argv[2])
    files = sorted(p for p in registry.glob("*.md") if not p.name.startswith("_") and p.name != "README.md")
    if not files:
        print(f"no frameworks found in {registry}", file=sys.stderr)
        return 1

    frameworks, failures = [], []
    for path in files:
        try:
            meta = read_frontmatter(path)
            errors = check(meta, path)
        except (ValueError, yaml.YAMLError) as exc:
            errors = [str(exc)]
        if errors:
            failures += [f"{path.name}: {e}" for e in errors]
            continue
        entry = {k: meta[k] for k in REQUIRED}
        entry.update({k: meta.get(k, []) for k in OPTIONAL_LISTS})
        entry["file"] = path.name
        frameworks.append(entry)

    if failures:
        print("framework registry is invalid:\n  " + "\n  ".join(failures), file=sys.stderr)
        return 1

    vocabulary = {}
    for fw in frameworks:
        for ptype in fw["problemTypes"]:
            vocabulary.setdefault(ptype, []).append(fw["id"])
    vocabulary = {k: sorted(v) for k, v in sorted(vocabulary.items())}

    out_dir.mkdir(parents=True, exist_ok=True)
    header = f"# Generated by scripts/frameworks/build-index.py from {registry.name}/ - do not edit.\n"
    index = {"frameworkCount": len(frameworks), "problemTypes": vocabulary, "frameworks": frameworks}
    (out_dir / "framework-index.yaml").write_text(
        header + yaml.safe_dump(index, sort_keys=False, allow_unicode=True, width=100), encoding="utf-8")
    (out_dir / "framework-vocabulary.yaml").write_text(
        header + yaml.safe_dump({"problemTypes": vocabulary}, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8")
    print(json.dumps({"frameworks": len(frameworks), "problemTypes": len(vocabulary), "outDir": str(out_dir)}))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
